run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: false  # Type assertions are common in generic code
    check-blank: false  # Allow blank identifier for deliberate error ignoring
  
  govet:
    enable:
      - atomic
      - bools
      - buildtag
      - composites
      - copylocks
      - deepequalerrors
      - errorsas
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - shift
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - fieldalignment  # Micro-optimization, not critical for correctness
      - shadow  # Can be overly strict
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

